{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "traverse.fullname" . }}
  labels: {{ include "traverse.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: traverse
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: http
      protocol: TCP
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
{{- end }}
