{{- if or .Values.auth.token .Values.auth.tokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traverse.fullname" . }}
  labels: {{ include "traverse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.token }}
  control-plane-token: {{ .Values.auth.token | quote }}
  {{- end }}
  {{- if .Values.auth.tokens }}
  control-plane-tokens: {{ .Values.auth.tokens | quote }}
  {{- end }}
{{- end }}
