{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "traverse.fullname" . }}
  labels: {{ include "traverse.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: traverse
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}
