{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "traverse" }}
  labels:
    app: traverse
automountServiceAccountToken: true
{{- end }}
